name: Build and deploy Gobot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: lazarodm/gobot-godot-br:${{ github.sha }},lazarodm/gobot-godot-br:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'Login to azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy app settings'
        uses: azure/appservice-settings@v1
        with:
          app-name: 'gobot-godot-br-v2'
          app-settings-json: '[
            {"name":"DISCORD_APP_ID","value":"${{ secrets.DISCORD_APP_ID }}", "slotSetting": false},
            {"name":"DISCORD_PUBLIC_KEY","value":"${{ secrets.DISCORD_PUBLIC_KEY }}", "slotSetting": false},
            {"name":"DISCORD_BOT_TOKEN","value":"${{ secrets.DISCORD_BOT_TOKEN }}", "slotSetting": false},
            {"name":"DOCKER_REGISTRY_SERVER_URL","value":"https://index.docker.io/v1", "slotSetting": false},
            {"name":"GODOT_PATH","value":"/opt/bin/godot", "slotSetting": false},
            {"name":"SCRIPTS_PATH","value":"/tmp", "slotSetting": false},
          ]'

      - name: 'Deploy to Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: lazarodm/fortune-api:${{ github.sha }}
